easy_admin:
    site_name: 'InterPool'
    design:
        menu:
            - label: 'Utilisateur'
              children: ['User', 'Professeurs']
            - label: 'Listes des notes'
              children: ['Note']
            - label: 'Listes des matières'
              children: ['Matiere']
    entities:
       # List the entity class name you want to manage
        User:
            class: App\Entity\User
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'email', type: 'email'}
                    - { property: 'username', type: 'text'}
                    - { property: 'password', type: 'hidden'}
                    - { property: 'roles'}
                    - { property: 'sortRole', type: 'text' }
                    - { property: 'subjects'}
            list:
                dql_filter: "entity.sortRole = 'ROLE_STUDENT'"
                fields:
                    - { property: 'username', label: 'Utisateurs' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'roles', label: 'Roles' }
                    - { property: 'subjects', label: 'Matieres' }
                    - { property: 'notes', label: 'Notes' }



        Matiere:
            class: App\Entity\Matiere
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                dql_filter: "entity.sortRole = 'ROLE_TEACHER'"
                fields:
                    - { property: 'user'}
                    - { property: 'nomMatiere', type: 'text', label: Matière}
                    - { property: 'students', type: 'entity', type_options: {class: 'App\Entity\User',by_reference: false} }


            list:
                fields:
                    - { property: 'nomMatiere', label: 'Matiere' }
                    - { property: 'user', label: 'Professeurs' }

        Note:
            class: App\Entity\Note
            list:
                fields:
                    - { property: 'user', label: 'Etudiant' }
                    - { property: 'note', label: 'Note' }
                    - { property: 'commentaire', label: 'Commentaire' }
                    - { property: 'matieres', label: 'Matieres' }
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'user', label: Etudiant}
                    - { property: 'note'}
                    - { property: 'commentaire', type: 'text'}
                    - { property: 'matieres'}

        Professeurs:
            class: App\Entity\User
            list:
                dql_filter: "entity.sortRole = 'ROLE_TEACHER'"
                fields: ['email', 'username','roles', 'matieres']
            form:  # <-- 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'email', type: 'email'}
                    - { property: 'username', type: 'text'}
                    - { property: 'password', type: 'hidden'}
                    - { property: 'roles'}
                    - { property: 'sortRole', type: 'text' }
                    - { property: 'matieres'}

